DROP TABLE	Chantier CASCADE CONSTRAINTS; 
DROP TABLE	Employe	CASCADE CONSTRAINTS;
DROP TABLE	Vehicule CASCADE CONSTRAINTS;
DROP TABLE	Visite CASCADE CONSTRAINTS;
DROP TABLE	Transporter	CASCADE CONSTRAINTS;