DROP TABLE Segment CASCADE CONSTRAINTS;
DROP TABLE Salle CASCADE CONSTRAINTS;
DROP TABLE Poste CASCADE CONSTRAINTS;
DROP TABLE Logiciel CASCADE CONSTRAINTS;
DROP TABLE Installer CASCADE CONSTRAINTS;
DROP TABLE Types CASCADE CONSTRAINTS;